---
consul_version: '1.0.7'
consul_install_remotely: true
consul_addresses:
  dns: "{{ ansible_default_ipv4.address }}"
  http: "{{ ansible_default_ipv4.address }}"
  https: "{{ ansible_default_ipv4.address }}"
