---

- name: Install packages Debian
  become: true
  apt:
    name: '{{ item }}'
  with_items:
    - python-pip
  when:
    - ansible_os_family == 'Debian'

- name: Add EPEL repo'
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
  when:
    - ansible_os_family == 'RedHat'

- name: Install packages RedHat
  become: true
  yum:
    name: '{{ item }}'
  with_items:
    - python-pip
  when:
    - ansible_os_family == 'RedHat'

- name: Install pip packages
  become: true
  pip:
    name: '{{ item }}'
  with_items:
    - docker
